/** Immutable installed-release store and atomic pointer authority. */
import { copyFileSync, existsSync, lstatSync, mkdirSync, readlinkSync, readdirSync, renameSync, rmSync, symlinkSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { verifyMaterializedPayload, verifyReleaseArtifact, materializeVerifiedArtifact } from './artifact.mjs';

const inside = (parent, path) => { const rel = relative(resolve(parent), resolve(path)); return rel && !rel.startsWith('..') && !isAbsolute(rel); };
const logicalId = ({ release, artifact }) => `${release.version}+${release.source_commit.slice(0, 12)}-${artifact.payload.manifest_sha256.slice(0, 16)}`;
const checkpoint = (onCheckpoint, name) => { if (onCheckpoint) onCheckpoint(name); };
export function releaseStorePaths(installStore) { const root = resolve(installStore); return { root, releases: join(root, 'releases'), current: join(root, 'current'), previous: join(root, 'previous') }; }
function realDirectory(path, label) { const info = lstatSync(path); if (!info.isDirectory() || info.isSymbolicLink()) throw new Error(`${label} must be a real directory`); }
function ensureStore(paths) { mkdirSync(paths.root, { recursive: true }); realDirectory(paths.root, 'install store'); mkdirSync(paths.releases, { recursive: true }); realDirectory(paths.releases, 'releases parent'); }
function targetFor(paths, id) { return join(paths.releases, id, 'payload'); }
function atomicLink(link, target, paths) { if (!inside(paths.releases, target)) throw new Error('Release pointer target is outside releases'); const relativeTarget = relative(dirname(link), target); if (!relativeTarget || isAbsolute(relativeTarget)) throw new Error('Release pointer must use a relative target'); const temp = join(dirname(link), `.${basename(link)}.tmp-${process.pid}-${Date.now()}`); try { symlinkSync(relativeTarget, temp); const resolved = resolve(dirname(temp), readlinkSync(temp)); if (resolved !== resolve(target)) throw new Error('Temporary pointer target mismatch'); renameSync(temp, link); } finally { if (existsSync(temp)) rmSync(temp, { force: true }); } }
export function resolveReleasePointer(pointer, installStore) { const paths = releaseStorePaths(installStore); if (!existsSync(pointer)) return null; const info = lstatSync(pointer); if (!info.isSymbolicLink()) throw new Error(`Release pointer is not a symlink: ${pointer}`); const raw = readlinkSync(pointer); if (isAbsolute(raw)) throw new Error(`Release pointer must be relative: ${pointer}`); const target = resolve(dirname(pointer), raw); if (!inside(paths.releases, target) || !target.endsWith('/payload')) throw new Error(`Release pointer is outside finalized payloads: ${pointer}`); const result = verifyMaterializedPayload(target); const id = basename(dirname(target)); if (id !== logicalId(result)) throw new Error('Release pointer logical identity mismatch'); return { id, path: target, ...result }; }
export function verifyInstalledRelease(releaseId, installStore) { const paths = releaseStorePaths(installStore); if (!/^[0-9A-Za-z.+-]+$/.test(releaseId)) throw new Error('Unsafe release id'); const payload = targetFor(paths, releaseId); if (!inside(paths.releases, payload)) throw new Error('Release payload escapes store'); const result = verifyMaterializedPayload(payload); if (releaseId !== logicalId(result)) throw new Error('Installed release directory identity mismatch'); return { id: releaseId, path: payload, ...result }; }
export function installVerifiedArtifact({ archive, installStore, onCheckpoint = null }) { const paths = releaseStorePaths(installStore); ensureStore(paths); checkpoint(onCheckpoint, 'before-artifact-verify'); const verified = verifyReleaseArtifact(archive); checkpoint(onCheckpoint, 'after-artifact-verify'); const id = logicalId(verified), finalRoot = join(paths.releases, id); if (existsSync(finalRoot)) { const installed = verifyInstalledRelease(id, paths.root); if (installed.release.source_commit !== verified.release.source_commit || installed.artifact.payload.manifest_sha256 !== verified.artifact.payload.manifest_sha256) throw new Error('Existing release collision has different logical content'); return { ...installed, reused: true }; }
  const tempRoot = join(paths.releases, `.install-${id}-${process.pid}-${Date.now()}`);
  try { checkpoint(onCheckpoint, 'during-materialization'); const { root } = materializeVerifiedArtifact(archive, tempRoot); const materialized = verifyMaterializedPayload(root); if (logicalId(materialized) !== id) throw new Error('Materialized release identity changed'); const payload = join(tempRoot, 'payload'); renameSync(root, payload); mkdirSync(join(tempRoot, 'artifact')); copyFileSync(archive, join(tempRoot, 'artifact', basename(archive))); copyFileSync(`${archive}.sha256`, join(tempRoot, 'artifact', `${basename(archive)}.sha256`)); verifyMaterializedPayload(payload); checkpoint(onCheckpoint, 'before-final-release-rename'); renameSync(tempRoot, finalRoot); checkpoint(onCheckpoint, 'after-final-release-rename'); return { ...verifyInstalledRelease(id, paths.root), reused: false }; } catch (error) { if (existsSync(tempRoot)) rmSync(tempRoot, { recursive: true, force: true }); throw error; }
}
export function activateRelease(releaseId, installStore, { validate = verifyInstalledRelease, onCheckpoint = null } = {}) { const paths = releaseStorePaths(installStore), next = validate(releaseId, paths.root), active = resolveReleasePointer(paths.current, paths.root); if (active?.id === releaseId) return { current: next, previous: resolveReleasePointer(paths.previous, paths.root), unchanged: true }; checkpoint(onCheckpoint, 'before-previous-switch'); if (active) atomicLink(paths.previous, active.path, paths); checkpoint(onCheckpoint, 'after-previous-switch'); checkpoint(onCheckpoint, 'before-current-switch'); atomicLink(paths.current, next.path, paths); checkpoint(onCheckpoint, 'after-current-switch'); try { checkpoint(onCheckpoint, 'before-post-activation-validation'); const checked = validate(releaseId, paths.root); return { current: checked, previous: active, unchanged: false }; } catch (error) { if (active) atomicLink(paths.current, active.path, paths); throw error; } }
export function rollbackRelease(installStore, { validate = verifyInstalledRelease } = {}) { const paths = releaseStorePaths(installStore), previous = resolveReleasePointer(paths.previous, paths.root); if (!previous) throw new Error('No valid previous release for rollback'); const target = validate(previous.id, paths.root), current = resolveReleasePointer(paths.current, paths.root); if (!current) throw new Error('Current pointer is missing or invalid'); atomicLink(paths.current, target.path, paths); try { const checked = validate(target.id, paths.root); atomicLink(paths.previous, current.path, paths); return { current: checked, previous: current }; } catch (error) { atomicLink(paths.current, current.path, paths); throw error; } }
export function listInstalledReleases(installStore) { const paths = releaseStorePaths(installStore); if (!existsSync(paths.releases)) return []; realDirectory(paths.releases, 'releases parent'); const current = resolveReleasePointer(paths.current, paths.root)?.id, previous = resolveReleasePointer(paths.previous, paths.root)?.id; return readdirSync(paths.releases).filter((id) => !id.startsWith('.')).map((id) => { const release = verifyInstalledRelease(id, paths.root); return { id, version: release.release.version, source_commit: release.release.source_commit, manifest_sha256: release.artifact.payload.manifest_sha256, current: id === current, previous: id === previous }; }); }
export function releaseEntrypoint(releaseId, installStore, command = 'ocode') { const release = verifyInstalledRelease(releaseId, installStore); const names = { ocode: 'ocode.mjs', harness: 'harness.mjs', orient: '../../orientation/bin/orient.mjs' }; if (!names[command]) throw new Error('Unknown release entrypoint'); return command === 'orient' ? join(release.path, 'orientation/bin/orient.mjs') : join(release.path, 'harness-runtime/bin', names[command]); }
